### ISSUE TITLE
isAnonymouslyFramed naming should probably be anonymouslyFramed

### ISSUE THREAD

**Issue by domenic** [WICG/anonymous-iframe#7]
See https://w3ctag.github.io/design-principles/#naming-booleans and other precedents like `crossOriginIsolated` or `originAgentCluster` which do not have the `is` prefix.

**Comment by ArthurSonzogni** [comment]
Okay, let's proceed with this change. Thanks for letting us know!

**Comment by ArthurSonzogni** [comment]
https://chromium-review.googlesource.com/c/chromium/src/+/3790944
