### ISSUE TITLE
window.anonymous reference leftover in explainer

### ISSUE THREAD

**Issue by domenic** [WICG/anonymous-iframe#8]
> The state of the anonymous flag is exposed to the [Window](https://fetch.spec.whatwg.org/#concept-request-window) through a read-only constant attribute:
>
> window.anonymous
>
> It is true for [Window](https://fetch.spec.whatwg.org/#concept-request-window) loaded immediately inside an anonymous iframe, or deeper below it.

This should presumably be `window.isAnonymouslyFramed`.

**Comment by ArthurSonzogni** [comment]
Thanks! I will make an update.
